title: Dutch Farmhouses of Brooklyn — by Bicycle!
baseurl:

parameters:
  max_distance: 8000 # meters

style:
  primary-color: "#de5f1b"
  secondary-color: "#346166"

defaults:
  - scope:
      path: ""
    values:
      layout:

  - scope:
      path: ""
      type: locations
    values:
      layout: location

collections:
  locations:
    output: true
    permalink: /locations/:name/
