title: Dutch Farmhouses of Brooklyn — by Bicycle!
baseurl: /dutch-farmhouses-of-brooklyn
assetsurl: https://bertspaan.nl/dutch-farmhouses-of-brooklyn-assets/

parameters:
  max_distance: 8000 # meters
  map:
    tileUrl: "https://api.mapbox.com/styles/v1/nypllabs/cj2gmix25005o2rpapartqm07/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibnlwbGxhYnMiLCJhIjoiSFVmbFM0YyJ9.sl0CRaO71he1XMf_362FZQ"
    attribution: "&copy; Mapbox, &copy; OpenStreetMap"

style:
  primary_color: "#de5f1b"
  secondary_color: "#346166"

defaults:
  - scope:
      path: ""
    values:
      layout:

  - scope:
      path: ""
      type: locations
    values:
      layout: location

collections:
  locations:
    output: true
    permalink: /locations/:name/
